# This is workflow to build and deploy angular app on github pages
name: Build and Deploy on github pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with:
              node-version: '16.x'
          - run: yarn install
          - run: yarn build:prod
          - run: git config --global user.email "persan78@hotmail.com"
          - run: git config --global user.name "Choupa-web"
          - run: npm run publish
