name: CI-CD
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v1
            with:
              node-version: '16.x'
          - run: yarn install
          - run: npm run build:prod
          - uses: rlespinasse/github-slug-action@v2.x
          - uses: actions/upload-artifact@v2
            with:
              name: ng9-github-actions-netlify-${{ github.ref }}-${{ github.run_id }}-${{ github.run_number }}
              path: ./dist/ng9-github-actions-netlify
