name: Merge on develop CI-CD
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v1
            with:
              node-version: '16.x'
          - run: yarn install
          - run: npm run build --prod
          - uses: rlespinasse/github-slug-action@v3
          - uses: actions/upload-artifact@v2
            with:
              name: artifact-develop-${{ github.run_number }}
              path: ./dist
