name: on pull request creation
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: yarn install
      - run: npm run build --prod
      - uses: rlespinasse/github-slug-action@v4
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-develop-${{ github.run_number }}
          path: ./dist
